.changeset/five-melons-move.md, README.md, index.js, package-lock.json, src/mapDescriptionToComment.js, src/registerTransforms.js, src/transformFontWeights.js, src/transformLineHeight.js
@six7 @jorenbroekema 
addresses https://github.com/tokens-studio/sd-transforms/issues/11
For this SD json
```json
"lineHeights": {
"0": {
"value": "AUTO",
"type": "lineHeights",
"description": "line height description"
},
"1": {
"value": "130%",
"type": "lineHeights",
"description": "line height description"
},
"2": {
"value": "120%",
"type": "lineHeights",
"description": "line height description"
}
},
```
the output is like 
```js
export const lineHeights0 = "AUTO"; // line height description
export const lineHeights1 = 1.3; // line height description
export const lineHeights2 = 1.2; // line height description
```
=> Adds line height transform, Adds description to comment transform

.changeset/angry-squids-tie.md, src/registerTransforms.js
The `ts/size/px` transform function is missing specific token types that it should include.
This pull requests adds `sizing` and `borderWidth`. It also sorts the token types list in the same order as what is in the documentation, https://docs.tokens.studio/available-tokens/available-tokens.
=> Include missing token types in to/size transform function

.changeset/another-changeset.md, .changeset/purple-falcons-knock.md, README.md, index.js, src/compose/transformTypography.js, src/css/transformTypography.js, src/registerTransforms.js
Fixes https://github.com/tokens-studio/sd-transforms/issues/17
Also adds a typography shorthand transformer for Jetpack Compose. It uses [`TextStyle`](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/TextStyle) and maps the properties of the typography tokens to the properties in Compose.
I could not find a way to match `paragraphSpacing`, it therefore is skipped.
=> Scope the typography shorthand to CSS

.changeset/lazy-mangos-buy.md, README.md, package-lock.json, src/registerTransforms.ts
This PR removes `attribute/cti` transform as it is not needed nor used. 
See https://github.com/tokens-studio/sd-transforms/issues/33 for more details
=> remove attribute/cti transform as it is not needed nor used

.changeset/early-ghosts-sort.md, src/checkAndEvaluateMath.ts, test/checkAndEvaluateMath.test.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/39
=> fix: evaluateAndCheckMath no trailing space for normal values with spaces

.changeset/wild-cougars-kneel.md, src/css/transformTypography.ts, src/registerTransforms.ts, test/integration/tokens/typography.tokens.json, test/integration/typography-references.test.ts
@six7  can you review this one? It seemed like the token `original.value` was a conscious choice, but I can't really figure out why you would want the untransformed/unresolved value to transform, this won't work for reference values?
Let me know if there's other cases I should test before committing to this change.
fixes https://github.com/tokens-studio/sd-transforms/issues/70
=> fix: use resolved/transformed value rather than original in transforms

.changeset/fuzzy-shoes-hug.md, package-lock.json, package.json, rollup/cjs.config.mjs
fixes https://github.com/tokens-studio/sd-transforms/issues/111
=> fix: CJS interop rollup option for handling default exports

.changeset/modern-tips-invite.md, package-lock.json, src/css/transformTypography.ts, src/utils/has-whitespace.ts, test/integration/math-in-complex-values.test.ts, test/integration/object-value-references.test.ts, test/spec/css/transformTypographyForCSS.spec.ts
hi there,
it is recommended to set Font Family Name in quotes if the name has whitespaces in its name. --> [Link](https://www.w3.org/TR/css-fonts-3/#family-name-value).
I made a first draft of how you could achieve this in the typography-shorthand transformer. I updated the test.
Input
```
Font-Family Name: 'Custom Font'
fontWeight: 'light',
fontSize: '20',
lineHeight: '1.5',
```
**Current Output**
```
"300 20px/1.5 Custom Font"
```
**Expected Output**
```
"300 20px/1.5 'Custom Font'"
```
Let me if there are any questions about this issue.
=> fix: set font family name in quotes

.changeset/empty-pots-call.md, src/css/transformTypography.ts, src/transformFontWeights.ts, src/transformLineHeight.ts, src/transformOpacity.ts, src/utils/is-nothing.ts, test/spec/transformFontWeights.spec.ts, test/spec/transformLineHeight.spec.ts, test/spec/transformOpacity.spec.ts
This fixes the return types of some of the token types. 
Previously, things such as fontWeight token types were returned as `string`, where they should be `number`.  (from my viewpoint at least 😄.
Fixed return type:
- opacity
- lineHeight
- fontWeight
=> fix return types of some token types

.changeset/three-onions-relate.md, CONTRIBUTING.md, src/mapDescriptionToComment.ts, test/spec/mapDescriptionToComment.spec.ts
Currently, having `/n` in a token description will cause the `ts/descriptionToComment` transform to create invalid output. This PR just strips `\n` (and also `\r` to be safe) from the comments.
Also fixes a npm command typo in `CONTRIBUTING.md`
```json
"heading-large": {
"value": {
"fontFamily": "Roboto",
"fontWeight": "Regular",
"lineHeight": "36",
"fontSize": "28",
"letterSpacing": "0"
},
"type": "typography",
"description": "The headline text styles are intended for a wide range of use cases when large text is needed including:\n\nPage headings/titles,\nSection headings/titles,\nCard headings/titles"
},
```
```js
export const GENERAC_HEADING_LARGE = "400 28px/36 Roboto"; // The headline text styles are intended for a wide range of use cases when large text is needed including:
Page …
```
=> fix: Strip line breaks from comments to ensure valid output

.changeset/olive-cooks-destroy.md, src/css/transformHEXRGBa.ts, test/spec/css/transformHEXRGBa.spec.ts
The regex to check for rgba hex strings allowed for whitespaces between the comma and the alpha value but no other spacing was allowed: `rgba\((?<hex>#.+?),\s*?(?<alpha>\d.*?)\)`
However, in Tokens Studio upon for example setting a rgba value where the hex code refers to another token, the plug-in will automatically add a space before and after the token. This means that you end up with something like `rgba( {base.Shadow} , 0.5)` which will no longer work with the aforementioned regex.
For now, the fix is that our designers make sure in their way of working that they manually remove those whitespaces but that's an extra step and prone to human error. It would be much easier to allow for whitespacing before and after the hex value with a regex like: …
=> fix(transformHEXRGBAForCSS): allow whitespacing surrounding the hex code

.changeset/eighty-eggs-smile.md, .changeset/tidy-pots-enjoy.md, README.md, package.json, src/css/transformTypography.ts, src/registerTransforms.ts, test/spec/css/transformFontFamilies.spec.ts
Where a `type` composite token referenced a css variable for font name (and the source font needed quoting)
and `outputReferences` is set to true, the output css variable incorrectly retained the quotes around the `'var()'`.
For example:
```css
--cone-type-600-mono: var(--global-font-weight-regular) var(--cone-font-size-300)/var(--cone-line-height-2x-dense) 'var(--cone-font-sf-mono)';
```
instead of
```css
--cone-type-600-mono: var(--global-font-weight-regular) var(--cone-font-size-300)/var(--cone-line-height-2x-dense) var(--cone-font-sf-mono);
```
I made a workaround
```javascript
// The style dictionary transformer wraps font family names which contains spaces in quotes.
// Because we have outputReferences set to true, the formatter replaces the quote *contents* with a reference …
```
=> Add transform: font family token value to valid CSS

.changeset/tiny-poets-doubt.md, .changeset/wild-actors-roll.md, package-lock.json, src/checkAndEvaluateMath.ts, src/css/transformTypography.ts, src/parsers/add-font-styles.ts, src/parsers/expand-composites.ts, src/registerTransforms.ts, src/transformFontWeights.ts, test/integration/expand-composition.test.ts, test/integration/object-value-references.test.ts, test/integration/tokens/expand-composition.tokens.json, test/integration/tokens/object-value-references.tokens.json, test/spec/checkAndEvaluateMath.spec.ts, test/spec/css/transformTypographyForCSS.spec.ts, test/spec/parsers/add-font-styles.spec.ts, test/spec/transformFontWeights.spec.ts
**Summary:** 
This adds a parser function to add a `fontStyle` to typography tokens based on the `fontWeight` value.
**Problem:**
When working with `tokens-studio`, it's kind of difficult to work with `fontWeights` and certainly when combined with something like `italics`. 
**Proposed solution:**
I was wondering if it would be an idea to solve this in the custom parser. I'm thinking you could strip out "italic" from the `fontWeight` and add it to a typography token as a separate property. After which, it could be expanded if you'd like that.
So
```json
"my-typography-token": {
"value": {
"fontFamily": "Roboto",
"fontWeight": "ExtraBold Italic",
"lineHeight": "16px",
"fontSize": "12px"
},
"type": "typography"
}
```
would be (after parsing)
```json
"my-typography-token": {
"value": { …
```
=> add a parser function to add fontStyle to typography tokens

.changeset/tall-horses-kneel.md, src/checkAndEvaluateMath.ts, test/spec/checkAndEvaluateMath.spec.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/168
=> fix: split more than 3 multi-value without spacers properly

.changeset/hot-planets-whisper.md, package-lock.json, src/checkAndEvaluateMath.ts, src/css/transformBorder.ts, src/css/transformShadow.ts, src/css/transformTypography.ts, test/spec/checkAndEvaluateMath.spec.ts
This seems like a slightly better way to handle it?
=> fix for checkAndEvaluateMath as it currently crashed on boolean expressions

.changeset/sharp-lamps-smash.md, src/checkAndEvaluateMath.ts, test/spec/checkAndEvaluateMath.spec.ts
This test shouldn't remove the quotes of the nested string I think?
=> Fix test of check-and-evaluate-math

.changeset/wild-trainers-laugh.md, src/parsers/add-font-styles.ts
The `alwaysAddFontStyle` isn't re-passed in the `recurse` function.
=> Fix recurse in add-font-styles

.changeset/unlucky-zebras-type.md, src/parsers/add-font-styles.ts, src/transformFontWeights.ts, test/spec/parsers/add-font-styles.spec.ts
Some fonts (such as Roboto) don't explicitly name their regular italic weight `Regular Italic`. (It's just named `Italic` instead of `Regular Italic`.)
Not sure how you'd like to handle this case, but I've already added a test case.
=> Fix add-font-styles with italic weight that don't explicitly state they are regular

.changeset/fuzzy-beers-sell.md, .changeset/nice-tips-attack.md, .changeset/seven-comics-fly.md, .changeset/silver-lobsters-know.md, README.md, package.json, src/TransformOptions.ts, src/index.ts, src/parsers/add-font-styles.ts, src/parsers/expand-composites.ts, src/parsers/parse-tokens.ts, src/registerTransforms.ts, test/integration/sd-transforms.test.ts, test/integration/utils.ts, test/spec/parsers/expand.spec.ts
- addAttributeCTI opton
- structuredClone over Object.assign shallow copying
- expose parseTokens parser function
- make expandComposites function arguments order consistent with the other parser functions
=> feat: addAttributeCTI option, add parseTokens funtions, swap args, structuredClone

.changeset/slow-wolves-notice.md, src/css/transformTypography.ts, test/integration/sd-transforms.test.ts, test/integration/tokens/sd-transforms.tokens.json, test/spec/css/transformFontFamilies.spec.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/222
Escape any occurences of ' automatically in the quoteWrapWhitespacedFont to resolve the issue with special character `.
**escapeApostrophes** is a new function that takes a string and replaces every apostrophe with an escaped apostrophe. It uses the replace method with a regular expression /'/g that matches all occurrences of an apostrophe and replaces them with \' (the double backslash is needed because backslash is an escape character in JavaScript strings).
In the quoteWrapWhitespacedFont (exisiting function), the input string is first passed to escapeApostrophes to ensure all apostrophes are properly escaped. Then, the rest of the function proceeds as before, but uses the escaped string for the checks and final return …
=> resolve issue 222 (Suisse Int'l font family transform issue / special character transform)

.changeset/poor-singers-drop.md, package-lock.json, package.json, src/checkAndEvaluateMath.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/241
=> fix: use expr-eval fork to fix security issue

.changeset/thirty-chairs-end.md, package-lock.json, package.json, src/color-modifiers/transformColorModifiers.ts, src/registerTransforms.ts, test/integration/color-modifier-references.test.ts, test/integration/cross-file-refs.test.ts, test/integration/custom-group.test.ts, test/integration/exclude-parent-keys.test.ts, test/integration/expand-composition.test.ts, test/integration/math-in-complex-values.test.ts, test/integration/object-value-references.test.ts, test/integration/output-references.test.ts, test/integration/sd-transforms.test.ts, test/integration/swift-UI-color.test.ts, test/integration/tokens/color-modifier-references.tokens.json, test/spec/color-modifiers/transformColorModifiers.spec.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/211
=> fix: references inside color modifiers

.changeset/short-doors-warn.md, .changeset/ten-icons-argue.md, src/checkAndEvaluateMath.ts, test/spec/checkAndEvaluateMath.spec.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/48
TODO:
=> chore: add tests for more advanced math expressions

src/register.ts, test/spec/checkAndEvaluateMath.spec.ts
fixes some sloppiness I introduced here: https://github.com/tokens-studio/sd-transforms/pull/290
I wouldn't mind encapsulating platform config options inside an `options` property like we do for format-level options, it would be a bit more consistent.. But currently style-dictionary also doesn't do this for the platform config option "basePxFontSize" so doing it now would be inconsistent as well.
I think we should pull transform options passed through platform config into an "options" object though in the future but this would a small breaking change, so it will be style-dictionary v5. too bad I missed this for v4.
=> chore: small fix for platform config usage

.changeset/cool-windows-hang.md, .changeset/two-ads-confess.md, package-lock.json, package.json, src/index.ts, src/preprocessors/add-font-styles.ts, src/preprocessors/align-types.ts, test/integration/cross-file-refs.test.ts, test/integration/expand-composition.test.ts, test/integration/tokens/expand-composition.tokens.json, test/spec/preprocessors/add-font-styles.spec.ts, test/spec/register.spec.ts
=> fix: split fontWeight tokens font style properly into parent group

.changeset/giant-bears-drum.md, src/preprocessors/add-font-styles.ts, test/spec/preprocessors/add-font-styles.spec.ts
fixes https://github.com/tokens-studio/sd-transforms/issues/298
=> fix: do not add always add fontStyle for fontWeights

.changeset/brave-timers-burn.md, src/checkAndEvaluateMath.ts, test/spec/checkAndEvaluateMath.spec.ts
A recent PR (https://github.com/tokens-studio/sd-transforms/pull/49) broke the ability to evaluate math expressions **with** units.
```
roundTo(30px/5)
```
This PR changes the order of operations, so that both `eval-expr` and `postcss-calc-ast-parser` are applied to the expression without any units.
Furthermore I added some additional checks to increase the speed of the evaluation function.
=> fix: evaluate math expressions with units

test/integration/cross-file-refs.test.ts, test/integration/utils.ts
While exploring some of the transforms and their associated tests, I noticed the `init` function used to initialize `style-dictionary` (i.e., register `sd-transforms` and `dict.buildAllPlatforms()`) accepts an untyped function argument `transformOpts`.
This PR associates the `TransformOptions` type to this `transformOpts` argument.
In doing so, TypeScript began throwing an error within `cross-file-refs.test.ts` that the existing `expand` option passed to `init` isn't valid per the `TransformOptions` type. The tests pass regardless of whether `expand` is present or not in the provided options, which seems to indicate nothing consumes the property value. As such, I've removed `expand` from this test suite.
=> chore: add TransformOptions type to `init` in integration tests

.changeset/friendly-rats-listen.md, package-lock.json, package.json, src/index.ts, tsconfig.json
As discussed in issue #319 , this PR exposes the TransformOptions type. Further it fixes type definition file override errors, when running the build locally.
I packed the sd-transform package locally via `npm pack` and tested the import of the `TransformOption` type like this:
```typescript
import { TransformOptions } from '@tokens-studio/sd-transforms';
```
and it worked like expected!
=> Provide transform options type

.changeset/smart-pianos-destroy.md, src/index.ts, test/integration/expand-composition.test.ts, test/integration/tokens/expand-composition.tokens.json
letterSpacing is no longer a dimension token. I updated one of the test tokens to see if letterSpacing still acts properly. The tests have all passed.
=> letterSpacing is no longer a dimension token (#316)

.changeset/brave-poets-rest.md, package-lock.json, src/transformDimension.ts, test/spec/transformDimension.spec.ts
sd-transforms now supports introducing multiple values for size tokens. If '8 16' is transmitted, it is transformed to '8px 16px'. Before, that was only happening when a single value was written.
=> fixed multiple token dimension values(#320)

README.md
Verify example with dependencies:
"@tokens-studio/sd-transforms": "^1.2.9",
"style-dictionary": "^4.2.0"
and this tokenset:
```json
{
"core/colors": {
"colors": {
"red": {
"value": "#f00",
"type": "color"
}
}
},
"core/dimensions": {
"spacing": {
"5": {
"value": "20px",
"type": "dimension"
}
}
},
"$themes": [
{
"id": "6be618dc1cae3215f1793c74e72f3095e4de3527",
"name": "Light",
"group": "Theme",
"selectedTokenSets": {
"core/colors": "enabled"
}
},
{
"id": "28983d638284cad3d6ad7965ac4046e1f48f6588",
"name": "Dark",
"group": "Theme",
"selectedTokenSets": {
"core/dimensions": "enabled"
}
}
]
}
```
The output should be that you get a `tokens` folder with 2 files (`core/colors.json` and `core/dimensions.json`) each with their respective tokens contents, as well as an output of `vars-Dark.css` -> …
=> chore: add single-file multi-theme example
